Bundler/OrderedGems:
  Enabled: false

Layout/ArgumentAlignment:
  Exclude:
    - 'bin/**/*'

Layout/EmptyLineAfterGuardClause:
  Exclude:
    - 'bin/**/*'

Layout/HashAlignment:
  Exclude:
    - 'app/models/membership_application.rb'
    - 'app/models/membership_application/steps.rb'

Metrics/BlockLength:
  Max: 40
  Exclude:
    - 'spec/**/*'

Metrics/LineLength:
  Max: 120

Style/Documentation:
  Exclude:
    - 'app/controllers/**/*'
    - 'app/models/*'
    - 'app/mailers/*'
    - 'app/helpers/*'
    - 'config/**/*'
    - 'db/**/*'

Style/FrozenStringLiteralComment:
  Enabled: false

Style/StringLiterals:
  Exclude:
    - 'config/*.rb'
    - 'config/environments/*.rb'
    - 'db/**/*'
    - 'bin/*'
