version: 2.1
orbs:
  ruby: circleci/ruby@0.2.1

jobs:
  build:
    docker:
      - image: circleci/ruby:2.7.0-buster-node
        environment:
          PGHOST: 127.0.0.1
          PGUSER: forsa-test
          RAILS_ENV: test

      # Specify service dependencies here if necessary
      # CircleCI maintains a library of pre-built images
      # documented at https://circleci.com/docs/2.0/circleci-images/
      - image: circleci/postgres:9.6.9-alpine
        environment:
          POSTGRES_USER: forsa-test
          POSTGRES_DB: forsa_test
          POSTGRES_PASSWORD: ""

    executor: ruby/default
    steps:
      - checkout
      - run:
          name: Update bundler
          command: gem install bundler:2.1.4
      - run:
          name: Which bundler?
          command: bundle -v
      - ruby/load-cache
      - ruby/install-deps
      - ruby/save-cache
      - ruby/run-tests